# permissions for end users to view cloudaccountopenstacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sc
    app.kubernetes.io/managed-by: kustomize
  name: cloudaccountopenstack-viewer-role
rules:
- apiGroups:
  - spectrocloud.spectrocloud.com
  resources:
  - cloudaccountopenstacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spectrocloud.spectrocloud.com
  resources:
  - cloudaccountopenstacks/status
  verbs:
  - get
