# permissions for end users to edit cloudaccountcustoms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sc
    app.kubernetes.io/managed-by: kustomize
  name: cloudaccountcustom-editor-role
rules:
- apiGroups:
  - spectrocloud.spectrocloud.com
  resources:
  - cloudaccountcustoms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spectrocloud.spectrocloud.com
  resources:
  - cloudaccountcustoms/status
  verbs:
  - get
