# permissions for end users to view cloudaccountgcps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sc
    app.kubernetes.io/managed-by: kustomize
  name: cloudaccountgcp-viewer-role
rules:
- apiGroups:
  - spectrocloud.spectrocloud.com
  resources:
  - cloudaccountgcps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spectrocloud.spectrocloud.com
  resources:
  - cloudaccountgcps/status
  verbs:
  - get
