# permissions for end users to edit filters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sc
    app.kubernetes.io/managed-by: kustomize
  name: filter-editor-role
rules:
- apiGroups:
  - spectrocloud.spectrocloud.com
  resources:
  - filters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spectrocloud.spectrocloud.com
  resources:
  - filters/status
  verbs:
  - get
